### ISSUE TITLE
@Optional is broken

### ISSUE THREAD

**Issue by exaskye** [elytra/Concrete#32]
```
com.elytradev.concrete.network.exception.BadMessageException: Wire fields cannot be null (in class com.elytradev.correlated.storage.Prototype com.elytradev.correlated.network.inventory.TerminalActionMessage.subject)
	at com.elytradev.concrete.network.WireField.marshal(WireField.java:90)
	at com.elytradev.concrete.network.NetworkContext.lambda$getPacketFrom$1(NetworkContext.java:147)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.elytradev.concrete.network.NetworkContext.getPacketFrom(NetworkContext.java:147)
	at com.elytradev.concrete.network.Message.toServerboundVanillaPacket(Message.java:399)
	at com.elytradev.concrete.network.Message.sendToServer(Message.java:391)
	at com.elytradev.correlated.client.gui.GuiTerminal.tryAction(GuiTerminal.java:926)
	at com.elytradev.correlated.client.gui.GuiTerminal.mouseClicked(GuiTerminal.java:906)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1884)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
```
The field is marked Optional, and Concrete still considers a null illegal.

**Comment by darkevilmac** [comment]
Wouldn't @Nullable be a better annotation to use?

**Comment by exaskye** [comment]
nice ping

I prefer using custom annotations so that you can just look in the package of the library to find all the supported annotations.

**Comment by darkevilmac** [comment]
Fair enough.
